replicaCount: 1

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.eu-north-1.amazonaws.com/lesson-5-ecr
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

configMap:
  ALLOWED_HOSTS: "*"
  DB_ENGINE: django.db.backends.sqlite3
  DB_HOST: localhost
  DB_PORT: 5432
  DB_USER: user
  DB_NAME: db.sqlite3

secret:
  DB_PASSWORD: ""  # Override: --set secret.DB_PASSWORD=yourpassword

